services:
  easy-as-app:
    image: easy-as
    container_name: easy-as-app
    ports:
      - "4000:4000"
    depends_on:
      - proxy-mongo
    environment:
      NODE_ENV: production
      DB_CONN_STRING: mongodb://root:root@proxy-mongo:27017/as?authSource=admin&retryWrites=true&w=majority
      DB_NAME: as
