name: proxied_app
services:
  proxy_app:
      image: easy-proxy
      container_name: proxy_app
      ports:
        - "4001:4000"
      environment:
        NODE_ENV: production
        TARGET_SERVER: http://internalize:3000
        TARGET_BASE_PATH: /
        AUTH_SERVER: http://easy-as-app:4000
        AUTH_RENEW_PATH: /token/renew
        X_FORWARDED_HOST: localhost:4001 #must match internalize origin